export const queryKeys = {
  novels: {
    all: ["novels"] as const,
    list: (page: number, limit: number) => ["novels", "list", page, limit] as const,
    detail: (id: string) => ["novels", "detail", id] as const,
    chapters: (id: string) => ["novels", "chapters", id] as const,
    characters: (id: string) => ["novels", "characters", id] as const,
    characterResources: (id: string) => ["novels", "character-resources", id] as const,
    characterResourceContext: (id: string, chapterId: string) => ["novels", "character-resource-context", id, chapterId] as const,
    chapterTimeline: (id: string, chapterId: string) => ["novels", "chapter-timeline", id, chapterId] as const,
    characterRelations: (id: string) => ["novels", "character-relations", id] as const,
    characterCastOptions: (id: string) => ["novels", "character-cast-options", id] as const,
    characterDynamicsOverview: (id: string, chapterOrder?: number) => ["novels", "character-dynamics-overview", id, chapterOrder ?? "latest"] as const,
    characterCandidates: (id: string) => ["novels", "character-candidates", id] as const,
    characterMindState: (id: string, characterId: string) => ["novels", "character-mind-state", id, characterId] as const,
    characterDialogueSession: (id: string, characterId: string) => ["novels", "character-dialogue-session", id, characterId] as const,
    characterTimeline: (id: string, charId: string) => ["novels", "character-timeline", id, charId] as const,
    chapterTraces: (novelId: string, chapterId: string) => ["novels", "chapter-traces", novelId, chapterId] as const,
    pipelineJob: (id: string, jobId: string) => ["novels", "pipeline", id, jobId] as const,
    qualityReport: (id: string) => ["novels", "quality-report", id] as const,
    state: (id: string) => ["novels", "state", id] as const,
    latestStateSnapshot: (id: string) => ["novels", "state-snapshots", id, "latest"] as const,
    payoffLedger: (id: string, chapterOrder?: number) => ["novels", "payoff-ledger", id, chapterOrder ?? "latest"] as const,
    chapterStateSnapshot: (id: string, chapterId: string) => ["novels", "state-snapshots", id, chapterId] as const,
    chapterPlan: (id: string, chapterId: string) => ["novels", "chapter-plan", id, chapterId] as const,
    chapterAuditReports: (id: string, chapterId: string) => ["novels", "chapter-audit-reports", id, chapterId] as const,
    chapterEditorWorkspace: (id: string, chapterId: string) => ["novels", "chapter-editor-workspace", id, chapterId] as const,
    storylineVersions: (id: string) => ["novels", "storyline-versions", id] as const,
    volumeWorkspace: (id: string) => ["novels", "volume-workspace", id] as const,
    volumeVersions: (id: string) => ["novels", "volume-versions", id] as const,
    creativeDecisions: (id: string) => ["novels", "creative-decisions", id] as const,
    storyMacro: (id: string) => ["novels", "story-macro", id] as const,
    storyMacroState: (id: string) => ["novels", "story-macro-state", id] as const,
    autoDirectorTask: (id: string) => ["novels", "auto-director-task", id] as const,
    directorBookAutomation: (id: string) => ["novels", "director-book-automation", id] as const,
    autoDirectorTakeoverReadiness: (id: string) => ["novels", "auto-director-takeover-readiness", id] as const,
    directorRiskPolicy: (id: string) => ["novels", "director-risk-policy", id] as const,
    changeProposals: (id: string, filters = "all") => ["novels", "change-proposals", id, filters] as const,
    changeProposalDetail: (id: string, proposalId: string) => ["novels", "change-proposals", id, "detail", proposalId] as const,
    novelWorld: (id: string) => ["novels", "novel-world", id] as const,
    novelWorldSyncDiff: (id: string) => ["novels", "novel-world", id, "sync-diff"] as const,
    worldSlice: (id: string) => ["novels", "world-slice", id] as const,
    snapshots: (id: string) => ["novels", "snapshots", id] as const,
  },
  worlds: {
    all: ["worlds"] as const,
    detail: (id: string) => ["worlds", "detail", id] as const,
    structure: (id: string) => ["worlds", "structure", id] as const,
    templates: ["worlds", "templates"] as const,
    overview: (id: string) => ["worlds", "overview", id] as const,
    visualization: (id: string) => ["worlds", "visualization", id] as const,
    snapshots: (id: string) => ["worlds", "snapshots", id] as const,
    library: (params: string) => ["worlds", "library", params] as const,
    knowledgeDocuments: (id: string) => ["worlds", "knowledge-documents", id] as const,
  },
  knowledge: {
    documents: (params: string) => ["knowledge", "documents", params] as const,
    detail: (id: string) => ["knowledge", "detail", id] as const,
    chapters: (documentId: string, versionId: string) => ["knowledge", "chapters", documentId, versionId] as const,
    ragJobs: (params: string) => ["knowledge", "rag-jobs", params] as const,
    ragHealth: ["knowledge", "rag-health"] as const,
  },
  bookAnalysis: {
    list: (params: string) => ["book-analysis", "list", params] as const,
    detail: (id: string) => ["book-analysis", "detail", id] as const,
    characters: (id: string) => ["book-analysis", "characters", id] as const,
  },
  writingFormula: {
    all: ["writing-formula"] as const,
    detail: (id: string) => ["writing-formula", "detail", id] as const,
  },
  styleEngine: {
    profiles: ["style-engine", "profiles"] as const,
    profile: (id: string) => ["style-engine", "profile", id] as const,
    templates: ["style-engine", "templates"] as const,
    antiAiRules: ["style-engine", "anti-ai-rules"] as const,
    effectiveAntiAiRules: (params: string) => ["style-engine", "anti-ai-rules", "effective", params] as const,
    bindings: (params: string) => ["style-engine", "bindings", params] as const,
  },
  genres: {
    all: ["genres"] as const,
  },
  drama: {
    projects: ["drama", "projects"] as const,
    project: (id: string) => ["drama", "project", id] as const,
    characters: (id: string) => ["drama", "characters", id] as const,
    characterLibrary: (projectId?: string) => ["drama", "character-library", projectId ?? "global"] as const,
    storyboard: (storyboardId: string) => ["drama", "storyboard", storyboardId] as const,
    videoProviders: ["drama", "video-providers"] as const,
    ttsProviders: ["drama", "tts-providers"] as const,
  },
  storyModes: {
    all: ["story-modes"] as const,
  },
  titles: {
    all: ["titles"] as const,
    list: (params: string) => ["titles", "list", params] as const,
  },
  baseCharacters: {
    all: ["base-characters"] as const,
    detail: (id: string) => ["base-characters", "detail", id] as const,
  },
  llm: {
    providers: ["llm", "providers"] as const,
  },
  images: {
    task: (taskId: string) => ["images", "task", taskId] as const,
    assets: (sceneType: "character" | "novel_cover" | "book_analysis_character", sceneId: string) => ["images", "assets", sceneType, sceneId] as const,
  },
  tasks: {
    overview: ["tasks", "overview"] as const,
    list: (params: string) => ["tasks", "list", params] as const,
    detail: (kind: string, id: string) => ["tasks", "detail", kind, id] as const,
    recoveryCandidates: ["tasks", "recovery-candidates"] as const,
    autoDirectorFollowUpDetail: (directorTaskId: string) => ["tasks", "auto-director-follow-up", directorTaskId] as const,
    directorTaskSnapshot: (directorTaskId: string) => ["tasks", "director-task-snapshot", directorTaskId] as const,
    directorRuntime: (directorTaskId: string) => ["tasks", "director-runtime", directorTaskId] as const,
    directorIssuePolicy: (novelId: string) => ["novels", "director-issue-policy", novelId] as const,
  },
  autoDirectorFollowUps: {
    overview: ["auto-director-follow-ups", "overview"] as const,
    list: (params: string) => ["auto-director-follow-ups", "list", params] as const,
    detail: (directorTaskId: string) => ["auto-director-follow-ups", "detail", directorTaskId] as const,
  },
  agentRuns: {
    list: (params: string) => ["agent-runs", "list", params] as const,
    detail: (id: string) => ["agent-runs", "detail", id] as const,
  },
  agentCatalog: ["agent-catalog"] as const,
  promptWorkbench: {
    catalog: (params: string) => ["prompt-workbench", "catalog", params] as const,
    preview: (promptKey: string) => ["prompt-workbench", "preview", promptKey] as const,
    materials: (params: string) => ["prompt-workbench", "materials", params] as const,
    slotOverrides: (params: string) => ["prompt-workbench", "slot-overrides", params] as const,
    slotReconcile: (params: string) => ["prompt-workbench", "slot-reconcile", params] as const,
    templateOverride: (params: string) => ["prompt-workbench", "template-overrides", params] as const,
    contextReferences: (params: string) => ["prompt-workbench", "context-references", params] as const,
  },
  creativeHub: {
    threads: ["creative-hub", "threads"] as const,
    state: (threadId: string) => ["creative-hub", "state", threadId] as const,
    history: (threadId: string) => ["creative-hub", "history", threadId] as const,
  },
  settings: {
    apiKeys: ["settings", "api-keys"] as const,
    llmSelection: ["settings", "llm-selection"] as const,
    apiKeyBalances: ["settings", "api-key-balances"] as const,
    rag: ["settings", "rag"] as const,
    ragEmbeddingModels: (provider: string) => ["settings", "rag", "embedding-models", provider] as const,
    styleEngineRuntime: ["settings", "style-engine-runtime"] as const,
    modelRoutes: ["settings", "model-routes"] as const,
    modelRouteConnectivity: ["settings", "model-route-connectivity"] as const,
    structuredFallback: ["settings", "structured-fallback"] as const,
    autoDirectorChannels: ["settings", "auto-director-channels"] as const,
    autoDirectorIssuePolicy: ["settings", "auto-director-issue-policy"] as const,
    autoDirectorApprovalPreferences: ["settings", "auto-director-approval-preferences"] as const,
    pendingReviewAutoPromotion: ["settings", "pending-review-auto-promotion"] as const,
    autoDirectorRiskPolicy: ["settings", "auto-director-risk-policy"] as const,
    quickSetup: ["settings", "quick-setup"] as const,
  },
  onboarding: {
    firstNovel: ["onboarding", "first-novel"] as const,
  },
  novelsKnowledge: {
    bindings: (id: string) => ["novels", "knowledge-documents", id] as const,
  },
};
